CREATE DATABASE syshub;

CREATE USER rafael WITH PASSWORD 'SYSHUB_TEO1';
ALTER ROLE rafael SET client_encoding TO 'utf8';
ALTER ROLE rafael SET default_transaction_isolation TO 'read committed';
ALTER ROLE rafael SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE syshub TO rafael;

CREATE TABLE Rol(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO Rol (nombre) VALUES ('ESTUDIANTE'),('ADMINISTRADOR'),('MODERADOR'),('AUXILIAR');

CREATE TABLE Usuario(
	carnet VARCHAR(9) PRIMARY KEY,
	nombre VARCHAR(250) NOT NULL,
	rol INTEGER NOT NULL,
	email VARCHAR(150) UNIQUE NOT NULL,
	estado BOOL NOT NULL DEFAULT true,
	password VARCHAR(60) NOT NULL,
	CONSTRAINT rol_usuario FOREIGN KEY (rol) REFERENCES Rol(id)
);
